application: staevtangel
version: 1
runtime: go
api_version: go1

default_expiration: "30d"

skip_files:
 - app\.yaml
 - .*Makefile

handlers:
 - url: /
   script: _go_app
   login: required
 
 - url: /admin
   script: _go_app
   login: admin
 
 - url: /data
   script: _go_app

 - url: /favicon.ico
   static_files: /favicon.ico
   upload: /favicon.ico

# Support files

 - url: /css/
   static_dir: css
   login: required
 
 - url: /css/admin.css
   static_files: css/admin.css
   upload: css/admin.css
   login: admin

 - url: /imgs/
   static_dir: imgs
   login: required
 
 - url: /imgs
   static_files: imgs/delete.png
   upload: imgs/delete.png
   login: admin

 - url: /js/
   static_dir: js
   login: required
 
 - url: /js/admin.js
   static_files: js/admin.js
   upload: js/admin.js
   login: admin
   
