application: staevtangel
version: 1
runtime: go
api_version: go1

default_expiration: "30d"

skip_files:
 - app\.yaml
 - .*Makefile

handlers:
 - url: /
   script: _go_app
   login: required

 - url: /favicon.ico
   static_files: /favicon.ico
   upload: /favicon.ico
   
